# Generated by Django 3.0.4 on 2020-03-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankhapp', '0002_auto_20200325_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('task_id', models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField(max_length=500)),
                ('assigned_to', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('task_duration', models.CharField(max_length=10)),
                ('task_status', models.CharField(choices=[('unassigned', 'UNASSIGNED'), ('assigned', 'ASSIGNED'), ('completed', 'COMPLETED')], default='unassigned', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
