# Generated by Django 3.0.4 on 2020-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankhapp', '0003_auto_20200326_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='task_duration',
            field=models.CharField(choices=[('1 hr', '1'), ('2 hr', '2'), ('3 hr', '3'), ('4 hr', '4'), ('5 hr', '5')], default='1 hr', max_length=10),
        ),
    ]
